name: "Validation And Formatting"
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Download repo
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        name: Setup Python
      - uses: actions/cache@v4
        name: Cache
        with:
          path: |
            ~/.cache/pip
          key: custom-component-ci
      - uses: "hacs/action@main"
        name: HACS validation
        with:
          category: "integration"
      # - uses: KTibow/ha-blueprint@stable
      #   name: CI
      #   if: github.event_name != 'pull_request'
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
